name: Publish and tagged release

on:
  push:
    tags:
      - '*'

jobs:
  publish-npm:
    name: 'Publish to NPM'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  tagged-release:
    needs: publish-npm
    name: 'Tagged Release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
